export const TODOS_CREATE = `CREATE TABLE IF NOT EXISTS todos (
    ID serial PRIMARY KEY,
    NAME VARCHAR (64) NOT NULL,
    DESCRIPTION VARCHAR (256),
    USER_ID INT NOT NULL,
    CREATED_ON TIMESTAMP NOT NULL,
    UPDATED_ON TIMESTAMP NOT NULL,
    STATUS VARCHAR (50) NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES users(ID) ON DELETE CASCADE
 );`

export const USERS_CREATE = `CREATE TABLE IF NOT EXISTS users (
    ID serial PRIMARY KEY,
    EMAIL VARCHAR (225) UNIQUE NOT NULL,
    PASSWORD VARCHAR (128) NOT NULL,
    CREATED_ON TIMESTAMP NOT NULL,
    UPDATED_ON TIMESTAMP NOT NULL
 );`