version: '3.9'
services:
  app:
    build: .
    depends_on:
      - db
    ports: 
      - "8000:8000"
    links:
      - db
    volumes:
      - .:/nodejsproject:rw
      - /nodejsproject/node_modules
    
      
  db:
    image: postgres:15.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/nodejsproject/data
volumes:
  db:
    driver: local